### ISSUE TITLE
Switching back to sandbox shells and selecting home not displaying tracks.

### ISSUE THREAD

**Issue by amaid** [Arlodotexe/strix-music#218] opened 2022-08-15 18:15 UTC
### Describe the bug

When switching shells, sandbox shell fails to to work properly.  The second time when you load the sandbox shell and click the home button it throws an exception on navigation service (NOTE: this navigation service will soon be nuked when app models refactor is executed.)

![image](https://user-images.githubusercontent.com/15306909/184691311-565e857b-76a8-46ea-aad0-28dd579a93f0.png)

### Affected area

- [ ] Strix Music SDK
- [X] Strix Music App

### Regression

It seems like an old lingering issue.

### Steps to reproduce

```text
1. Launch the app.
2. Switch to sandbox shells.
3. Switch to the zune/groove shell.
4. Switch back to the sandbox shell.
5. Click home button.
```

### Visual repro steps

https://user-images.githubusercontent.com/15306909/184692009-55d3ce09-5e4a-404e-ab58-6f314a577157.mp4

### Expected behavior

Sandbox shell should load the list of the tracks.

### Help us help you

Yes, I'd like to be assigned to work on this item.

**Comment by Arlodotexe** [comment] 2022-08-15 19:01
Duplicate of #193, closing

**Closed by Arlodotexe** 2022-08-15 19:01 UTC
Labels: bug, duplicate, regression
